"""
This type stub file was generated by pyright.
"""

import locale
from typing import TYPE_CHECKING
from typing import Any

"""Internationalization utilities."""
if TYPE_CHECKING:
    ...
_LOCALE = ...
class Translation:
    __slots__ = ...
    def __init__(self: Self) -> None:
        ...
    
    @property
    def locale(self: Self) -> str | Any:
        ...
    
    @locale.setter
    def locale(self: Self, loc: str) -> None:
        ...
    
    def __call__(self: Self, _key: str, **kwargs: str) -> str:
        ...
    


TRANSLATION = ...
